### PR TITLE
Update Services.yml

### PR DESCRIPTION
**Pull request by zipmishahl2**
NetBT is needed for NetBIOS to work properly

### CODE REVIEW

**Comment by imribiy** [comment]
Is this really needed to be come enabled by default for a gaming focused project?

**Comment by zipmishahl2** [comment]
yep

**Comment by Degl1** [comment]
What's the point of the pr if the commit doesn't align with the project's priorities?

**Comment by zipmishahl2** [comment]
Are you sure NetBT will work fine without NetBIOS? LOL.

**Pull request closed without merging**
